### ISSUE TITLE
Naming convention of delay methods

### ISSUE THREAD

**Issue by KacperKlys1** [e9ctrl/vd#12]
In method naming abbreviation of `delay` is `del`. In parameter naming convention `delay` is `dly`. We should agree on one version.

**Comment by mmllski** [comment]
I think it would be sensible to keep `dly` to be consistent with the three-letter field names in a parameter configuration file and ` delay` elsewhere.

**Comment by KacperKlys1** [comment]
Fixed while changing structure.
